services:
    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: php
        volumes:
            - .:/var/www/html
            - ./uploads:/var/www/uploads
        networks:
            - app-network

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./uploads:/var/www/uploads
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - app-network

networks:
    app-network:
        driver: bridge